[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "new_kedro_project"
version = "0.1.0"
description = "Laboratorio de procesamiento de imagenes con Kedro"
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "ipython>=8.10",
    "jupyterlab>=3.0",
    "notebook",
    "kedro~=1.3.1",
    "kedro-datasets",
    "Pillow>=10.0.0"
]

[project.optional-dependencies]
dev = [
    "pytest>=8.0.0",
    "ruff>=0.4.0"
]

[project.scripts]
new-kedro-project = "new_kedro_project.__main__:main"

[project.entry-points."kedro.hooks"]

[tool.setuptools.packages.find]
where = ["src"]
namespaces = false

[tool.kedro]
package_name = "new_kedro_project"
project_name = "New Kedro Project"
kedro_init_version = "1.3.1"
tools = "['None']"
example_pipeline = "False"
source_dir = "src"

[tool.kedro_telemetry]
project_id = "27fae96834e3468ea7566691aa43cdf4"

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.ruff]
line-length = 88
target-version = "py311"